import React, { useState } from 'react';
import { 
  HeartPulse, 
  ChevronDown, 
  ChevronUp, 
  Download, 
  Terminal, 
  AlertTriangle,
  Globe,
  CheckCircle2,
  Thermometer,
  Droplets,
  Activity
} from 'lucide-react';

const Diagnostics = ({ temp, moisture, stress }) => {
  const [loading, setLoading] = useState(false);
  const [advice, setAdvice] = useState(null);
  const [error, setError] = useState(null);
  const [jsonExpanded, setJsonExpanded] = useState(false);

  const runDiagnostics = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/diagnose', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          temperature: temp,
          moisture: moisture
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || 'Failed to complete diagnostic analysis.');
      }

      const data = await response.json();
      setAdvice(data);
    } catch (err) {
      console.error(err);
      setError(err.message || 'Server connection failed. Make sure backend is running.');
    } finally {
      setLoading(false);
    }
  };

  const getRiskClass = (level) => {
    if (!level) return '';
    return level.toLowerCase();
  };

  const handleDownload = () => {
    if (!advice) return;
    
    const dateStr = new Date(advice.timestamp || new Date()).toLocaleString();
    let report = `================================================
FARM DIAGNOSTIC REPORT - SMART FARM AI
Generated: ${dateStr}
================================================

TELEMETRY CONTEXT:
- Ambient Temperature: ${temp.toFixed(1)} °C
- Soil Moisture Level: ${moisture.toFixed(1)} %
- Computed Crop Stress: ${stress.toFixed(2)}
- Risk Level Diagnosis: ${advice.risk_level}

------------------------------------------------
ACTION PLAN (ENGLISH)
------------------------------------------------
Title: ${advice.english_title}

Steps:
${advice.english_steps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

------------------------------------------------
ACTION PLAN (HINDI / हिन्दी)
------------------------------------------------
Title: ${advice.hindi_title}

Steps:
${advice.hindi_steps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

================================================
Report exported by Agritech Diagnostic Dashboard.
================================================`;

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `farm_diagnostic_report_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <div className="page-header">
        <div className="page-title-section">
          <h1>🩺 Live AI Crop Diagnostics</h1>
          <p>Request immediate corrective agronomist steps generated by Gemini 2.5 Flash.</p>
        </div>
      </div>

      <div className="diagnose-layout">
        {/* Telemetry Summary Card */}
        <div className="glass-card diagnose-telemetry-summary">
          <h2 style={{ margin: '0 0 0.5rem 0', fontFamily: 'var(--font-title)' }}>🌿 Current State</h2>
          <p style={{ margin: '0 0 1rem 0', color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>
            The AI engine will run analysis on the live telemetry set below:
          </p>

          <div className="diag-stat-row">
            <span className="diag-stat-label">
              <Thermometer size={16} color="#f43f5e" /> Temperature
            </span>
            <span className="diag-stat-value temp">{temp.toFixed(1)} °C</span>
          </div>

          <div className="diag-stat-row">
            <span className="diag-stat-label">
              <Droplets size={16} color="#3b82f6" /> Soil Moisture
            </span>
            <span className="diag-stat-value moisture">{moisture.toFixed(1)} %</span>
          </div>

          <div className="diag-stat-row">
            <span className="diag-stat-label">
              <Activity size={16} color="#f59e0b" /> Crop Stress Index
            </span>
            <span className="diag-stat-value stress">{stress.toFixed(2)}</span>
          </div>

          <button 
            onClick={runDiagnostics} 
            disabled={loading} 
            className="action-btn-large"
            style={{ marginTop: '1rem' }}
          >
            {loading ? (
              <>
                <div className="spinner"></div>
                <span>Analyzing crop status...</span>
              </>
            ) : (
              <>
                <HeartPulse size={20} />
                <span>Run AI Diagnostics</span>
              </>
            )}
          </button>

          {error && (
            <div style={{ 
              marginTop: '1rem', 
              padding: '0.75rem', 
              backgroundColor: 'rgba(239, 68, 68, 0.1)', 
              border: '1px solid rgba(239, 68, 68, 0.2)',
              borderRadius: '8px',
              color: '#ef4444',
              fontSize: '0.85rem',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem'
            }}>
              <AlertTriangle size={16} />
              <span>{error}</span>
            </div>
          )}
        </div>

        {/* Diagnostic Results Card */}
        <div className="glass-card diagnose-results-card">
          {!advice ? (
            <div className="result-placeholder">
              <HeartPulse size={64} strokeWidth={1} />
              <div>
                <h3 style={{ margin: '0 0 0.5rem 0', color: '#fff', fontSize: '1.25rem', fontFamily: 'var(--font-title)' }}>
                  Awaiting Telemetry Analysis
                </h3>
                <p style={{ margin: 0, fontSize: '0.9rem', maxWidth: '400px', lineHeight: 1.4 }}>
                  Adjust moisture and temperature values in the sidebar or Overview panel, then click <strong>Run AI Diagnostics</strong> to query the agronomist models.
                </p>
              </div>
            </div>
          ) : (
            <>
              {/* Header with Risk Banner */}
              <div className="result-header-row">
                <div className="result-header-left">
                  <span style={{ fontWeight: 600, color: 'var(--color-text-muted)', fontSize: '0.9rem' }}>
                    Diagnostics Status:
                  </span>
                  <span className={`risk-pill ${getRiskClass(advice.risk_level)}`}>
                    {advice.risk_level} Risk Detected
                  </span>
                </div>
                <div style={{ color: 'var(--color-text-muted)', fontSize: '0.8rem', fontFamily: 'var(--font-mono)' }}>
                  {new Date(advice.timestamp).toLocaleTimeString()}
                </div>
              </div>

              {/* Side-by-side English/Hindi Content */}
              <div className="bilingual-columns">
                {/* English Column */}
                <div className="lang-panel">
                  <div className="lang-badge">
                    <Globe size={12} style={{ marginRight: '2px' }} /> English Advice
                  </div>
                  <h3 className="advice-title">{advice.english_title}</h3>
                  <ul className="advice-steps">
                    {advice.english_steps.map((step, idx) => (
                      <li key={idx}>{step}</li>
                    ))}
                  </ul>
                </div>

                {/* Hindi Column */}
                <div className="lang-panel">
                  <div className="lang-badge">
                    <Globe size={12} style={{ marginRight: '2px' }} /> हिन्दी सुझाव (Hindi)
                  </div>
                  <h3 className="advice-title" style={{ fontFamily: 'var(--font-sans)' }}>{advice.hindi_title}</h3>
                  <ul className="advice-steps">
                    {advice.hindi_steps.map((step, idx) => (
                      <li key={idx}>{step}</li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Collapsible Developer payload */}
              <div className="collapsible-container">
                <button 
                  onClick={() => setJsonExpanded(!jsonExpanded)}
                  className="collapsible-trigger"
                >
                  <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <Terminal size={16} color="#10B981" />
                    <span>View Developer Payload (Raw JSON)</span>
                  </span>
                  {jsonExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                </button>
                {jsonExpanded && (
                  <div className="collapsible-content">
                    <pre className="json-block">
                      {JSON.stringify(advice, null, 2)}
                    </pre>
                  </div>
                )}
              </div>

              {/* Footer Downloads */}
              <div className="diag-footer-actions">
                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#10b981', fontSize: '0.85rem', fontWeight: 600 }}>
                  <CheckCircle2 size={16} /> Verified Agronomy Logic
                </div>
                <button 
                  onClick={handleDownload} 
                  className="action-btn-secondary"
                >
                  <Download size={16} />
                  <span>Download Diagnostic Report</span>
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </>
  );
};

export default Diagnostics;
